language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN='9bef2888-0603-416c-92a6-3eb08e05d871'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - butcher_1996@mail.ru
    on_success: never # default: change
    on_failure: always # default: always